core/urls.py
from django.urls import path

from core.views import PlantCreateView, main

app_name = 'core'

urlpatterns = [
    path('', main, name='list'),
    path('create', PlantCreateView.as_view(), name='create')
]

plants/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models


class Plant(models.Model):
    SMALL = 0
    MEDIUM = 1
    LARGE = 2

    SIZES = (
        (SMALL, 'Маленький'),
        (MEDIUM, 'Средний'),
        (LARGE, 'Большой'),
    )

    title = models.CharField('название', max_length=255)
    color = models.CharField('цвет', max_length=255)
    size = models.PositiveSmallIntegerField('размер', choices=SIZES)
    area = models.CharField('Место произростания', max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.color} {self.title}'

    class Meta:
        verbose_name = 'Растение'
        verbose_name_plural = 'Растения'

core/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from core.models import Plant


class PlantForm(forms.ModelForm):
    helper = FormHelper()
    helper.add_input(Submit('submit', 'Сохранить', css_class='btn-primary'))
    helper.form_method = 'POST'

    class Meta:
        model = Plant
        fields = '__all__'

core/views.py
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView

from core.models import Plant
from .forms import PlantForm


def main(request):
    plants = Plant.objects.all()
    return TemplateResponse(request, 'core/list.html', context={'plants': plants})


class PlantCreateView(CreateView):
    model = Plant
    template_name = 'core/form.html'
    form_class = PlantForm
    success_url = reverse_lazy('core:list')

core/templates/core/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Список растений{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-6">
      {% crispy form %}
    </div>
  </div>
{% endblock content %}

core/templates/core/list.html
{% extends 'base.html' %}

{% block title %}Список растений{% endblock title %}

{% block content %}
  {% for plant in plants %}
    <h2>{{ plant.color }} {{ plant.title }}</h2>
    <p>Размер: {{ plant.get_size_display }}</p>
  {% endfor %}

  <a href="{% url 'core:create' %}" class="btn btn-primary">Добавить новое растение</a>
{% endblock content %}

templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title>
  {% bootstrap_css %}
</head>
<body>
<div class="container pt-5">
  {% block content %}
  {% endblock content %}
</div>
</body>
</html>